config/routes.rb
Rails.application.routes.draw do
  root 'posts#index' 
  
  resources :posts do
    get :search, on: :collection 
  end  
  resources :comments, only: %i[create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :author, :body, presence: true
  
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  include PgSearch  
  extend FriendlyId

  validates :title, :author, :body, presence: true

  has_many :comments, dependent: :destroy

  friendly_id :title, use: :slugged

  pg_search_scope :search, 
    against: %i[title author body],
    associated_against: { comments: %i[body] }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create  
    comment = Comment.create!(comments_params)

    redirect_to comment.post, notice: 'O seu comentário  foi enviado'
  end 

  private

  def comments_params
    params.require(:comment).permit(:post_id, :author, :body)
  end  
end    

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.order(created_at: :desc)
  end

  def search
    @posts = Post.search(search_params[:q])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @comments = @post.comments.order(created_at: :desc)
    @comment = Comment.new
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'O post foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @post }
      else
        flash.now[:alert] = @post.errors.full_messages.to_sentence
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'O post foi atualizado com sucesso.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'O post foi removido com sucesso' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :author, :body)
    end

    def search_params
      params.permit(:q)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_pack_tag 'application', media: 'all' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <div class="bg-primary text-center text-white mb-4 p-4">
      <%= link_to root_path, class: 'text-white' do %>
        <h1 class='display-4'>Blog</h1>
      <% end %>
      
      <p class='lead'>Olá, aqui você encontrará artigos sobre programação, tecnologia e carreira.</p>
    </div>

    <div class='container'>
      <% flash.each do |type, message| %>
        <div class='alert alert-<%= type == 'alert' ? 'danger' : 'success' %> alert-dismissible fade show' role='alert'>
          <%= message %>
          <button type='button' class='close' data-dismiss='alert' aria-label='Close'>
            <span aria-hidden='true'>&times;</span>
          </button>
        </div>
      <% end %>

      <div class='row'>
        <div class='col-4 offset-8'>
          <div class='search'>
            <%= form_with url: search_posts_path, method: :get, local: true, class: 'form-inline' do |form| %>
              <div class='form-group mx-3 mb-3'>
                <%= form.search_field :q, class: 'form-control', required: true,
                  placeholder: 'Busca', value: params[:q] %>
              </div>

              <%= form.submit 'Buscar', class: 'btn btn-primary mb-3',
                data: { disable_with: 'Buscando...' } %>
            <% end %>
          </div>
        </div>
      </div>

      <%= yield %>
    </div>

    <footer class='bg-primary text-white text-center mt-5 p-4'>
      Copyright © Fernando <%= Date.current.year%>
    </footer>
  </body>
</html>

app/views/pages/index.html.erb
<h1>Pages#index</h1>
<p>Find me in app/views/pages/index.html.erb</p>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :title %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :author %>
    <%= form.text_field :author, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= form.label :body %>
    <%= form.text_area :body, class: 'form-control', rows: 5 %>
  </div>
  
  <%= form.submit class: 'btn btn-primary', data: {disable_with: 'Criando..'} %>  
<% end %>

app/views/posts/_post.html.erb
<div class='card bg-light mb-3'>
  <div class='card-body'>
    <h4><%= link_to post.title, post %></h4>

    <div class='text-muted mb-2'>
      <em>Por <%= post.author %> (<%= l post.created_at, format: :short %>)</em>
    </div>

    <p><%= post.body.truncate(200) %></p>

    <p class='text-muted'><%= pluralize(post.comments.count, 'Comentário') %></p>

    <%= link_to 'Ler Artigo', post, class: 'btn btn-primary' %>
    <%= link_to 'Editar', edit_post_path(post), class: 'btn btn-secondary' %>
    <%= link_to 'Apagar', post, method: :delete, class: 'btn btn-danger',
      data: { confirm: 'Você tem certeza?' } %>
  </div>
</div>

app/views/posts/edit.html.erb
<h1>Editar Post</h1>

<%= render 'form', post: @post %>

app/views/posts/index.html.erb
<% @posts.each do |post| %>
  <%= render post %>
<% end %>

<%# O trecho acima pode ser substituido por: `render @posts` %>

<hr>

<div class='text-right'>
  <%= link_to 'Criar novo post', new_post_path, class: 'btn btn-success' %>
</div>

app/views/posts/new.html.erb
<h1>Novo Post</h1>

<%= render 'form', post: @post %>

app/views/posts/search.html.erb
<h2 class="text-muted">
  <% if @posts.any? %>
    <%= pluralize(@posts.count, 'resultado') %> encontrados:
  <% else %>
    Nenhum resultado encontrado.
  <% end %>
</h2>

<% @posts.each do |post| %>
  <%= render post %>
<% end %>

app/views/posts/show.html.erb
<div class='shadow p-5 bg-light rounded'>
  <div class='text-center mb-5'>
    <h1><%= @post.title %></h1>

    <p class='text-muted'>
      <strong>Por <%= @post.author %></strong> <br>
      <%= l @post.created_at, format: :long %>
    </p>
  </div>

  <div class='px-5'>
    <%= @post.body.gsub('\n', '<br>').html_safe %>
  </div>
</div>

<div class='m-5'>
  <div class='text-center'>
    <h4>
      <%= pluralize(@post.comments.count, 'comentário') %>

      <% if @post.comments.none? %>
        <span class='badge badge-success'>Seja o primeiro a comentar</span>
      <% end %>  
    </h4>
  </div>

  <div class='shadow-sm m-3 p-3 bg-light rounded'>
    <%= form_with model: @comment, local: true do |form| %>
      <%= form.hidden_field :post_id, value: @post.id %>

      <div class="form-group">
        <%= form.label :author %>
        <%= form.text_field :author, class: 'form-control', require: true %>
      </div>

      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 3, require: true %>
      </div>

      <%= form.submit 'Enviar', class: 'btn btn-primary', data: {disable_with: 'Enviando..'} %>  
    <% end %>
  </div>

  <% @comments.each do |comment| %>
    <div class='shadow-sm m-3 p-3 bg-light rounded'>
      <div class='row'>
        <div class='col'>
          <strong><%= comment.author %></strong>
        </div>

        <div class='col text-right'>
          <em data-toggle='tooltip' data-placement='top' title='<%= l comment.created_at, format: :long %>'>
            <%= time_ago_in_words comment.created_at %> atrás
          </em>
        </button>
        </div>
      </div>

      <hr>

      <%# Sempre que usarmos \n (como na linha abaixo), precisamos usar áspas duplas %>
      <%= sanitize(comment.body.gsub("\n", '<br>')).html_safe %>
    </div>
  <% end %>
</div>

  